### ISSUE TITLE
Swin backbone trained weights

### ISSUE THREAD

**Issue by YangJae96** [fredzzhang/pvic#56]
Hi. Thank you for your great work

Is only ResNet-50 backbone available for inference?
Could you please provided the Swin-L backbone model weights if possible?!

I would like the evaluate the results and use it for custom data for inference!

Thanks in advance.

**Comment by fredzzhang** [comment]
Hi @YangJae96,

Unfortunately we did not save the checkpoints with larger backbones due to storage reasons. You can find the fine-tuned object detector with Swin-L [here](https://drive.google.com/file/d/1wge-CC1Fx67EHOSXyHGHvrqvMva2jEkr/view). With this, you should be able to train the HOI detector yourself. Using the `--use-checkpoint` flag significantly reduces memory requirement.

Let me know if you have trouble reproducing the results.

Cheers,
Fred.

**Comment by YangJae96** [comment]
@fredzzhang  HI,

In your paper, you used 8 GPU with batch size 2. 

Can I ask why?!

And also, I only have 1 GPU... will the performance drop significantly when I use only 1 GPU with a more larger batch-size like 32?

**Comment by fredzzhang** [comment]
Hi @YangJae96,

I don't think the performance will drop significantly unless the batch size gets too low.

Fred.
