### ISSUE TITLE
How to inference with the advanced H-Defm-DETR-SwinL model

### ISSUE THREAD

**Issue by safsfsvvea** [fredzzhang/pvic#62]
Thank you very much for your excellent work!
I use 
DETR=advanced python inference.py --backbone swin_large \
                            --drop-path-rate 0.5 \
                            --num-queries-one2one 900 \
                            --num-queries-one2many 1500 \
                            --resume outputs/pvic-h-defm-detr-swinL-hicodet/best.pth \
                            --index 4050  \
                            --action 111 
but it seems that the score of the interaction is too low. The outputs/pvic-h-defm-detr-swinL-hicodet/best.pth can be tested with an accuracy of 44.4.

**Comment by safsfsvvea** [comment]
And even the detector does not give bbox in some test figures, so what should be the right input args?

**Comment by safsfsvvea** [comment]
I found that the main problem is that during inference the H-Defm-DETR-SwinL model has a much lower interaction score than the R50 detr model, and even in some simple images, since the interaction score is lower than 0.2, there is no bbox in the visualization. It is abnormal since the H-Defm-DETR-SwinL model should have a higher confidence.

**Comment by fredzzhang** [comment]
Hi @safsfsvvea,

Thanks for posting your investigation.

The reason that the `H-Defm-DETR-SwinL` model produces lower interaction scores is rooted in the object detection scores. Deformable DETR uses Sigmoid instead of Softmax to normalise the object detection scores. The latter tends to be over-confident in many occasions, resulting in many high object detection scores close to 1. Because these detection scores are directly integrated into the interaction scores, models using Deformable DETR will produce lower scores.

Hope that clears things up.

Cheers,
Fred.
